import type { BiomeId } from "../systems/BiomeIdentity";
import type { DungeonMaterials } from "./MaterialLibrary";

export type PortalArchitecture =
  | "megalithic"
  | "volcanic"
  | "glacial"
  | "ossuary"
  | "rootbound"
  | "funerary"
  | "industrial"
  | "shard"
  | "tidal"
  | "mycelial"
  | "liminal";

export type PortalSealKind = "bars" | "crossed" | "organic" | "bulkhead";

export interface BiomePortalProfile {
  biomeId: BiomeId;
  architecture: PortalArchitecture;
  signature: string;
  material: keyof DungeonMaterials;
  sealKind: PortalSealKind;
  frameColor: number;
  frameEmissive: number;
  frameEmissiveIntensity: number;
  frameMetalness: number;
  frameRoughness: number;
  accentColor: number;
  sealColor: number;
  deepColor: number;
  magicColor: number;
  brightColor: number;
  lightColor: number;
  beamColor: number;
  primaryArms: number;
  secondaryArms: number;
  radialFrequency: number;
  flowSpeed: number;
  counterSpeed: number;
  spiralSharpness: number;
  pillarFlare: number;
  crownThickness: number;
}

const PORTAL_PROFILES: Readonly<Record<BiomeId, Readonly<BiomePortalProfile>>> = Object.freeze({
  ancient: Object.freeze({
    biomeId: "ancient",
    architecture: "megalithic",
    signature: "Stepped rune monolith",
    material: "stone",
    sealKind: "bars",
    frameColor: 0x777d89,
    frameEmissive: 0x28344b,
    frameEmissiveIntensity: 0.28,
    frameMetalness: 0.12,
    frameRoughness: 0.82,
    accentColor: 0x9bc8ff,
    sealColor: 0x414a58,
    deepColor: 0x07142f,
    magicColor: 0x347fd3,
    brightColor: 0xb6dcff,
    lightColor: 0x77b9ff,
    beamColor: 0x7697bd,
    primaryArms: 3,
    secondaryArms: 7,
    radialFrequency: 13,
    flowSpeed: 1.55,
    counterSpeed: 1.05,
    spiralSharpness: 2.6,
    pillarFlare: 1.08,
    crownThickness: 1,
  }),
  molten: Object.freeze({
    biomeId: "molten",
    architecture: "volcanic",
    signature: "Lava fang caldera",
    material: "darkStone",
    sealKind: "crossed",
    frameColor: 0x321714,
    frameEmissive: 0xff3b08,
    frameEmissiveIntensity: 0.62,
    frameMetalness: 0.08,
    frameRoughness: 0.9,
    accentColor: 0xff8a22,
    sealColor: 0x70200f,
    deepColor: 0x1f0300,
    magicColor: 0xff4312,
    brightColor: 0xffd05c,
    lightColor: 0xff5b22,
    beamColor: 0xff6b24,
    primaryArms: 4,
    secondaryArms: 8,
    radialFrequency: 17,
    flowSpeed: 2.25,
    counterSpeed: 1.55,
    spiralSharpness: 3.2,
    pillarFlare: 1.32,
    crownThickness: 1.18,
  }),
  frost: Object.freeze({
    biomeId: "frost",
    architecture: "glacial",
    signature: "Crown of hanging ice",
    material: "ice",
    sealKind: "crossed",
    frameColor: 0x8fb8cd,
    frameEmissive: 0x2b7ca7,
    frameEmissiveIntensity: 0.34,
    frameMetalness: 0.04,
    frameRoughness: 0.26,
    accentColor: 0xd7f4ff,
    sealColor: 0x77a9c2,
    deepColor: 0x02101f,
    magicColor: 0x3bbde8,
    brightColor: 0xe3fbff,
    lightColor: 0x8fe8ff,
    beamColor: 0x9edcf2,
    primaryArms: 5,
    secondaryArms: 9,
    radialFrequency: 19,
    flowSpeed: 1.08,
    counterSpeed: 0.72,
    spiralSharpness: 4,
    pillarFlare: 0.86,
    crownThickness: 0.82,
  }),
  grim: Object.freeze({
    biomeId: "grim",
    architecture: "ossuary",
    signature: "Ossuary rib gate",
    material: "bone",
    sealKind: "bars",
    frameColor: 0x77745d,
    frameEmissive: 0x31441f,
    frameEmissiveIntensity: 0.22,
    frameMetalness: 0.02,
    frameRoughness: 0.96,
    accentColor: 0xa8d66f,
    sealColor: 0x514f3d,
    deepColor: 0x050d04,
    magicColor: 0x6b9d39,
    brightColor: 0xd7ed98,
    lightColor: 0xa2ca65,
    beamColor: 0x738c52,
    primaryArms: 2,
    secondaryArms: 5,
    radialFrequency: 11,
    flowSpeed: 0.86,
    counterSpeed: 1.34,
    spiralSharpness: 2.15,
    pillarFlare: 1.18,
    crownThickness: 0.9,
  }),
  verdant: Object.freeze({
    biomeId: "verdant",
    architecture: "rootbound",
    signature: "Living root arch",
    material: "wood",
    sealKind: "organic",
    frameColor: 0x334a2a,
    frameEmissive: 0x1d6f3d,
    frameEmissiveIntensity: 0.3,
    frameMetalness: 0,
    frameRoughness: 0.94,
    accentColor: 0x73e690,
    sealColor: 0x29492f,
    deepColor: 0x02130a,
    magicColor: 0x25b86f,
    brightColor: 0xa8ffbc,
    lightColor: 0x63ef9a,
    beamColor: 0x54aa78,
    primaryArms: 6,
    secondaryArms: 3,
    radialFrequency: 15,
    flowSpeed: 1.22,
    counterSpeed: 0.9,
    spiralSharpness: 2.45,
    pillarFlare: 1.14,
    crownThickness: 1.12,
  }),
  ash: Object.freeze({
    biomeId: "ash",
    architecture: "funerary",
    signature: "Censer funeral arch",
    material: "ceramic",
    sealKind: "bars",
    frameColor: 0x63594d,
    frameEmissive: 0x6a3017,
    frameEmissiveIntensity: 0.24,
    frameMetalness: 0.08,
    frameRoughness: 0.88,
    accentColor: 0xe59a55,
    sealColor: 0x51463b,
    deepColor: 0x120805,
    magicColor: 0xb65a27,
    brightColor: 0xffc57b,
    lightColor: 0xf0a05a,
    beamColor: 0xac7650,
    primaryArms: 3,
    secondaryArms: 4,
    radialFrequency: 9,
    flowSpeed: 0.74,
    counterSpeed: 0.58,
    spiralSharpness: 1.85,
    pillarFlare: 1.22,
    crownThickness: 1.06,
  }),
  iron: Object.freeze({
    biomeId: "iron",
    architecture: "industrial",
    signature: "Riveted pressure gate",
    material: "iron",
    sealKind: "bulkhead",
    frameColor: 0x4f565a,
    frameEmissive: 0x273238,
    frameEmissiveIntensity: 0.2,
    frameMetalness: 0.82,
    frameRoughness: 0.42,
    accentColor: 0xf0bd55,
    sealColor: 0x363d40,
    deepColor: 0x03090c,
    magicColor: 0x35a6be,
    brightColor: 0xcdf9ff,
    lightColor: 0x7be9ff,
    beamColor: 0x75959d,
    primaryArms: 8,
    secondaryArms: 4,
    radialFrequency: 21,
    flowSpeed: 1.82,
    counterSpeed: 1.82,
    spiralSharpness: 4.4,
    pillarFlare: 0.9,
    crownThickness: 1.22,
  }),
  obsidian: Object.freeze({
    biomeId: "obsidian",
    architecture: "shard",
    signature: "Fractured void crown",
    material: "crystal",
    sealKind: "crossed",
    frameColor: 0x1c1028,
    frameEmissive: 0x7d1c91,
    frameEmissiveIntensity: 0.52,
    frameMetalness: 0.22,
    frameRoughness: 0.24,
    accentColor: 0xe051ff,
    sealColor: 0x351343,
    deepColor: 0x07000e,
    magicColor: 0x891fc2,
    brightColor: 0xf0a6ff,
    lightColor: 0xd44cff,
    beamColor: 0x9f45b8,
    primaryArms: 7,
    secondaryArms: 11,
    radialFrequency: 23,
    flowSpeed: 2.05,
    counterSpeed: 1.1,
    spiralSharpness: 3.8,
    pillarFlare: 0.78,
    crownThickness: 0.72,
  }),
  sunken: Object.freeze({
    biomeId: "sunken",
    architecture: "tidal",
    signature: "Coral tide arch",
    material: "stone",
    sealKind: "organic",
    frameColor: 0x315d5b,
    frameEmissive: 0x0b7a79,
    frameEmissiveIntensity: 0.36,
    frameMetalness: 0.06,
    frameRoughness: 0.78,
    accentColor: 0x6fe4d5,
    sealColor: 0x275d60,
    deepColor: 0x001317,
    magicColor: 0x16a7a9,
    brightColor: 0xa7fff1,
    lightColor: 0x5de4da,
    beamColor: 0x4caaa5,
    primaryArms: 4,
    secondaryArms: 6,
    radialFrequency: 12,
    flowSpeed: 0.92,
    counterSpeed: 1.48,
    spiralSharpness: 2.25,
    pillarFlare: 1.28,
    crownThickness: 1.08,
  }),
  fungal: Object.freeze({
    biomeId: "fungal",
    architecture: "mycelial",
    signature: "Mycelium cap arch",
    material: "ceramic",
    sealKind: "organic",
    frameColor: 0x4f315d,
    frameEmissive: 0x2f9b7e,
    frameEmissiveIntensity: 0.4,
    frameMetalness: 0,
    frameRoughness: 0.84,
    accentColor: 0x7fffd0,
    sealColor: 0x533267,
    deepColor: 0x0d0317,
    magicColor: 0x8e48c3,
    brightColor: 0x8fffe0,
    lightColor: 0x7cf5d2,
    beamColor: 0x7d77a4,
    primaryArms: 5,
    secondaryArms: 10,
    radialFrequency: 18,
    flowSpeed: 1.35,
    counterSpeed: 0.8,
    spiralSharpness: 3.05,
    pillarFlare: 1.36,
    crownThickness: 1.26,
  }),
  backrooms: Object.freeze({
    biomeId: "backrooms",
    architecture: "liminal",
    signature: "Fluorescent threshold arch",
    material: "ceramic",
    sealKind: "bulkhead",
    frameColor: 0xb2a86d,
    frameEmissive: 0x77753c,
    frameEmissiveIntensity: 0.26,
    frameMetalness: 0.04,
    frameRoughness: 0.68,
    accentColor: 0xfff6a5,
    sealColor: 0x8b8151,
    deepColor: 0x111208,
    magicColor: 0xb8bc51,
    brightColor: 0xffffbd,
    lightColor: 0xfff3a0,
    beamColor: 0xc5b966,
    primaryArms: 9,
    secondaryArms: 2,
    radialFrequency: 25,
    flowSpeed: 0.58,
    counterSpeed: 2.2,
    spiralSharpness: 5.2,
    pillarFlare: 0.82,
    crownThickness: 0.88,
  }),
});

export function getBiomePortalProfile(id: BiomeId): Readonly<BiomePortalProfile> {
  return PORTAL_PROFILES[id];
}
