import type { DungeonMoodId } from "./DungeonMood";

export type BiomeParticleMotion =
  | "drift"
  | "rise"
  | "fall"
  | "orbit"
  | "flutter"
  | "spark"
  | "pulse"
  | "flicker"
  /** Fast ceiling-to-floor fall for drips, grit, blood, slime. */
  | "drip";

export type BiomeParticleShape =
  | "mote"
  | "streak"
  | "flake"
  | "ash"
  | "wisp"
  | "spore"
  | "shard"
  | "bubble"
  | "block"
  /** Teardrop / liquid bead from the ceiling. */
  | "drop"
  /** Loose grit or dirt crumb. */
  | "crumb";

export interface BiomeParticleLayerProfile {
  name: string;
  motion: BiomeParticleMotion;
  shape: BiomeParticleShape;
  color: number;
  colorAlt: number;
  minCount: number;
  maxCount: number;
  perFloor: number;
  sizeMin: number;
  sizeMax: number;
  opacity: number;
  speed: number;
  turbulence: number;
  flowX: number;
  flowY: number;
  flowZ: number;
  glow: boolean;
  wake: number;
}

export interface BiomeParticleProfile {
  label: string;
  support: BiomeParticleLayerProfile;
  signature: BiomeParticleLayerProfile;
  /**
   * Sparse ceiling precipitation: liquid drips, falling dirt, blood, slime,
   * or grit that matches the active biome.
   */
  ceiling: BiomeParticleLayerProfile;
}

const layer = (
  config: Omit<BiomeParticleLayerProfile, "minCount" | "maxCount" | "perFloor"> &
    Partial<Pick<BiomeParticleLayerProfile, "minCount" | "maxCount" | "perFloor">>,
): BiomeParticleLayerProfile => ({
  minCount: 240,
  maxCount: 680,
  perFloor: 0.34,
  ...config,
});

/** Sparse ceiling fallers — keep under the ambient field budget. */
const ceiling = (
  config: Omit<BiomeParticleLayerProfile, "minCount" | "maxCount" | "perFloor" | "wake" | "glow"> &
    Partial<Pick<BiomeParticleLayerProfile, "minCount" | "maxCount" | "perFloor" | "wake" | "glow">>,
): BiomeParticleLayerProfile => ({
  minCount: 48,
  maxCount: 160,
  perFloor: 0.08,
  wake: 0.12,
  glow: false,
  ...config,
});

const PROFILES: Record<DungeonMoodId, BiomeParticleProfile> = {
  ancient: {
    label: "dust, rune motes, and falling grit",
    support: layer({
      name: "Ancient limestone dust",
      motion: "drift",
      shape: "mote",
      color: 0xb9ad8f,
      colorAlt: 0x6f806f,
      sizeMin: 0.055,
      sizeMax: 0.17,
      opacity: 0.5,
      speed: 0.18,
      turbulence: 0.24,
      flowX: 0.025,
      flowY: 0.01,
      flowZ: -0.015,
      glow: false,
      wake: 0.42,
    }),
    signature: layer({
      name: "Ancient orbiting rune motes",
      motion: "orbit",
      shape: "block",
      color: 0xd6b66d,
      colorAlt: 0x74b6a1,
      minCount: 110,
      maxCount: 320,
      perFloor: 0.16,
      sizeMin: 0.05,
      sizeMax: 0.11,
      opacity: 0.62,
      speed: 0.22,
      turbulence: 0.34,
      flowX: 0,
      flowY: 0.015,
      flowZ: 0,
      glow: true,
      wake: 0.82,
    }),
    ceiling: ceiling({
      name: "Ancient ceiling grit",
      motion: "drip",
      shape: "crumb",
      color: 0x8a7a5e,
      colorAlt: 0x5a4e3a,
      minCount: 55,
      maxCount: 170,
      perFloor: 0.09,
      sizeMin: 0.05,
      sizeMax: 0.14,
      opacity: 0.55,
      speed: 0.42,
      turbulence: 0.12,
      flowX: 0.01,
      flowY: -0.9,
      flowZ: -0.01,
    }),
  },
  molten: {
    label: "embers, cinders, and slag drips",
    support: layer({
      name: "Molten falling cinders",
      motion: "fall",
      shape: "ash",
      color: 0x6f4430,
      colorAlt: 0xb75b32,
      sizeMin: 0.045,
      sizeMax: 0.14,
      opacity: 0.48,
      speed: 0.25,
      turbulence: 0.32,
      flowX: 0.03,
      flowY: -0.12,
      flowZ: 0.01,
      glow: false,
      wake: 0.5,
    }),
    signature: layer({
      name: "Molten rising embers",
      motion: "rise",
      shape: "streak",
      color: 0xff7a28,
      colorAlt: 0xffd27a,
      minCount: 220,
      maxCount: 620,
      perFloor: 0.3,
      sizeMin: 0.06,
      sizeMax: 0.2,
      opacity: 0.78,
      speed: 0.48,
      turbulence: 0.48,
      flowX: 0.05,
      flowY: 0.62,
      flowZ: -0.02,
      glow: true,
      wake: 0.9,
    }),
    ceiling: ceiling({
      name: "Molten slag drips",
      motion: "drip",
      shape: "drop",
      color: 0xff6a18,
      colorAlt: 0xc43a10,
      minCount: 40,
      maxCount: 140,
      perFloor: 0.07,
      sizeMin: 0.05,
      sizeMax: 0.15,
      opacity: 0.72,
      speed: 0.55,
      turbulence: 0.08,
      flowX: 0.02,
      flowY: -1,
      flowZ: 0,
      glow: true,
      wake: 0.2,
    }),
  },
  frost: {
    label: "snow, ice crystals, and melt drips",
    support: layer({
      name: "Frost powder snow",
      motion: "fall",
      shape: "flake",
      color: 0xc4ddea,
      colorAlt: 0x7899b4,
      minCount: 320,
      maxCount: 760,
      perFloor: 0.42,
      sizeMin: 0.045,
      sizeMax: 0.14,
      opacity: 0.62,
      speed: 0.2,
      turbulence: 0.52,
      flowX: 0.08,
      flowY: -0.34,
      flowZ: 0.02,
      glow: false,
      wake: 0.62,
    }),
    signature: layer({
      name: "Frost suspended ice crystals",
      motion: "flutter",
      shape: "shard",
      color: 0xeaf8ff,
      colorAlt: 0x72d4ff,
      minCount: 130,
      maxCount: 360,
      perFloor: 0.18,
      sizeMin: 0.05,
      sizeMax: 0.13,
      opacity: 0.58,
      speed: 0.16,
      turbulence: 0.42,
      flowX: -0.02,
      flowY: -0.05,
      flowZ: 0.035,
      glow: true,
      wake: 0.72,
    }),
    ceiling: ceiling({
      name: "Frost melt drips",
      motion: "drip",
      shape: "drop",
      color: 0xb8d8f0,
      colorAlt: 0x6a9aba,
      minCount: 60,
      maxCount: 180,
      perFloor: 0.1,
      sizeMin: 0.04,
      sizeMax: 0.12,
      opacity: 0.58,
      speed: 0.48,
      turbulence: 0.1,
      flowX: 0,
      flowY: -0.95,
      flowZ: 0.01,
    }),
  },
  grim: {
    label: "soot, grave wisps, and blood drips",
    support: layer({
      name: "Grim descending soot",
      motion: "fall",
      shape: "ash",
      color: 0x817d70,
      colorAlt: 0x3c463c,
      sizeMin: 0.06,
      sizeMax: 0.18,
      opacity: 0.5,
      speed: 0.15,
      turbulence: 0.38,
      flowX: -0.025,
      flowY: -0.16,
      flowZ: 0.018,
      glow: false,
      wake: 0.56,
    }),
    signature: layer({
      name: "Grim grave wisps",
      motion: "pulse",
      shape: "wisp",
      color: 0x8ebd8b,
      colorAlt: 0xc6d0aa,
      minCount: 90,
      maxCount: 260,
      perFloor: 0.13,
      sizeMin: 0.085,
      sizeMax: 0.22,
      opacity: 0.42,
      speed: 0.13,
      turbulence: 0.45,
      flowX: 0.01,
      flowY: 0.08,
      flowZ: -0.015,
      glow: true,
      wake: 0.94,
    }),
    ceiling: ceiling({
      name: "Grim blood drips",
      motion: "drip",
      shape: "drop",
      color: 0x6b1218,
      colorAlt: 0x3a0a0c,
      minCount: 50,
      maxCount: 150,
      perFloor: 0.08,
      sizeMin: 0.045,
      sizeMax: 0.13,
      opacity: 0.68,
      speed: 0.5,
      turbulence: 0.06,
      flowX: 0,
      flowY: -1,
      flowZ: 0,
    }),
  },
  verdant: {
    label: "pollen, fireflies, and sap drips",
    support: layer({
      name: "Verdant drifting pollen",
      motion: "drift",
      shape: "spore",
      color: 0xa8c77c,
      colorAlt: 0x6e8b58,
      minCount: 300,
      maxCount: 720,
      perFloor: 0.38,
      sizeMin: 0.06,
      sizeMax: 0.18,
      opacity: 0.58,
      speed: 0.2,
      turbulence: 0.56,
      flowX: 0.035,
      flowY: 0.025,
      flowZ: -0.02,
      glow: false,
      wake: 0.7,
    }),
    signature: layer({
      name: "Verdant fireflies",
      motion: "orbit",
      shape: "mote",
      color: 0xbaff78,
      colorAlt: 0x61e0ad,
      minCount: 110,
      maxCount: 300,
      perFloor: 0.14,
      sizeMin: 0.075,
      sizeMax: 0.17,
      opacity: 0.75,
      speed: 0.25,
      turbulence: 0.78,
      flowX: 0,
      flowY: 0.04,
      flowZ: 0,
      glow: true,
      wake: 1,
    }),
    ceiling: ceiling({
      name: "Verdant sap drips",
      motion: "drip",
      shape: "drop",
      color: 0x6a8a3a,
      colorAlt: 0x3d5a28,
      minCount: 45,
      maxCount: 140,
      perFloor: 0.08,
      sizeMin: 0.045,
      sizeMax: 0.13,
      opacity: 0.58,
      speed: 0.4,
      turbulence: 0.14,
      flowX: 0.02,
      flowY: -0.85,
      flowZ: -0.01,
    }),
  },
  ash: {
    label: "ashfall, embers, and falling dirt",
    support: layer({
      name: "Ash biome ashfall",
      motion: "fall",
      shape: "ash",
      color: 0x9b8c82,
      colorAlt: 0x544f50,
      minCount: 380,
      maxCount: 820,
      perFloor: 0.46,
      sizeMin: 0.065,
      sizeMax: 0.23,
      opacity: 0.62,
      speed: 0.24,
      turbulence: 0.64,
      flowX: 0.11,
      flowY: -0.3,
      flowZ: -0.035,
      glow: false,
      wake: 0.75,
    }),
    signature: layer({
      name: "Ash biome buried embers",
      motion: "rise",
      shape: "mote",
      color: 0xe79054,
      colorAlt: 0xf3c889,
      minCount: 80,
      maxCount: 230,
      perFloor: 0.11,
      sizeMin: 0.055,
      sizeMax: 0.14,
      opacity: 0.58,
      speed: 0.2,
      turbulence: 0.38,
      flowX: -0.02,
      flowY: 0.18,
      flowZ: 0.02,
      glow: true,
      wake: 0.76,
    }),
    ceiling: ceiling({
      name: "Ash ceiling dirt",
      motion: "drip",
      shape: "crumb",
      color: 0x6a5e56,
      colorAlt: 0x3e3836,
      minCount: 70,
      maxCount: 190,
      perFloor: 0.11,
      sizeMin: 0.055,
      sizeMax: 0.16,
      opacity: 0.58,
      speed: 0.38,
      turbulence: 0.18,
      flowX: 0.04,
      flowY: -0.8,
      flowZ: -0.02,
    }),
  },
  iron: {
    label: "metal dust, sparks, and rust water",
    support: layer({
      name: "Iron filings",
      motion: "fall",
      shape: "shard",
      color: 0x87919a,
      colorAlt: 0x4c5b62,
      sizeMin: 0.04,
      sizeMax: 0.13,
      opacity: 0.48,
      speed: 0.18,
      turbulence: 0.3,
      flowX: 0,
      flowY: -0.12,
      flowZ: 0.01,
      glow: false,
      wake: 0.5,
    }),
    signature: layer({
      name: "Iron magnetic sparks",
      motion: "spark",
      shape: "streak",
      color: 0x78c6e4,
      colorAlt: 0xffb45e,
      minCount: 130,
      maxCount: 380,
      perFloor: 0.18,
      sizeMin: 0.055,
      sizeMax: 0.16,
      opacity: 0.76,
      speed: 0.5,
      turbulence: 0.28,
      flowX: 0.18,
      flowY: 0.06,
      flowZ: -0.04,
      glow: true,
      wake: 1.12,
    }),
    ceiling: ceiling({
      name: "Iron rust water drips",
      motion: "drip",
      shape: "drop",
      color: 0x8a5a32,
      colorAlt: 0x5a3420,
      minCount: 50,
      maxCount: 150,
      perFloor: 0.08,
      sizeMin: 0.04,
      sizeMax: 0.12,
      opacity: 0.6,
      speed: 0.52,
      turbulence: 0.08,
      flowX: 0,
      flowY: -1,
      flowZ: 0.01,
    }),
  },
  obsidian: {
    label: "glass dust, splinters, and black grit",
    support: layer({
      name: "Obsidian glass dust",
      motion: "drift",
      shape: "shard",
      color: 0x6e4a73,
      colorAlt: 0x352a46,
      sizeMin: 0.055,
      sizeMax: 0.17,
      opacity: 0.5,
      speed: 0.14,
      turbulence: 0.25,
      flowX: -0.02,
      flowY: 0.02,
      flowZ: 0.02,
      glow: false,
      wake: 0.48,
    }),
    signature: layer({
      name: "Obsidian anti-gravity splinters",
      motion: "rise",
      shape: "shard",
      color: 0xbe65d1,
      colorAlt: 0xe08a89,
      minCount: 150,
      maxCount: 420,
      perFloor: 0.2,
      sizeMin: 0.06,
      sizeMax: 0.16,
      opacity: 0.68,
      speed: 0.22,
      turbulence: 0.34,
      flowX: 0.025,
      flowY: 0.28,
      flowZ: -0.02,
      glow: true,
      wake: 1.05,
    }),
    ceiling: ceiling({
      name: "Obsidian black grit",
      motion: "drip",
      shape: "crumb",
      color: 0x2a1e30,
      colorAlt: 0x4a3058,
      minCount: 55,
      maxCount: 160,
      perFloor: 0.09,
      sizeMin: 0.045,
      sizeMax: 0.13,
      opacity: 0.55,
      speed: 0.44,
      turbulence: 0.1,
      flowX: -0.01,
      flowY: -0.9,
      flowZ: 0.02,
    }),
  },
  sunken: {
    label: "drizzle, bubbles, and ceiling seepage",
    support: layer({
      name: "Sunken suspended droplets",
      motion: "fall",
      shape: "streak",
      color: 0x6c9996,
      colorAlt: 0x355f60,
      minCount: 300,
      maxCount: 720,
      perFloor: 0.4,
      sizeMin: 0.045,
      sizeMax: 0.15,
      opacity: 0.48,
      speed: 0.3,
      turbulence: 0.25,
      flowX: 0.015,
      flowY: -0.42,
      flowZ: 0.02,
      glow: false,
      wake: 0.58,
    }),
    signature: layer({
      name: "Sunken rising bubbles",
      motion: "rise",
      shape: "bubble",
      color: 0xa2e2d7,
      colorAlt: 0x59aeb1,
      minCount: 130,
      maxCount: 350,
      perFloor: 0.17,
      sizeMin: 0.07,
      sizeMax: 0.18,
      opacity: 0.55,
      speed: 0.28,
      turbulence: 0.5,
      flowX: 0.02,
      flowY: 0.36,
      flowZ: -0.01,
      glow: true,
      wake: 0.9,
    }),
    ceiling: ceiling({
      name: "Sunken ceiling seepage",
      motion: "drip",
      shape: "drop",
      color: 0x4a7a78,
      colorAlt: 0x2a4a4c,
      minCount: 80,
      maxCount: 220,
      perFloor: 0.13,
      sizeMin: 0.05,
      sizeMax: 0.15,
      opacity: 0.62,
      speed: 0.58,
      turbulence: 0.12,
      flowX: 0.015,
      flowY: -1,
      flowZ: 0.02,
    }),
  },
  fungal: {
    label: "spores, pulses, and slime drips",
    support: layer({
      name: "Fungal spore cloud",
      motion: "rise",
      shape: "spore",
      color: 0x8ec6a7,
      colorAlt: 0x8b6996,
      minCount: 360,
      maxCount: 820,
      perFloor: 0.45,
      sizeMin: 0.05,
      sizeMax: 0.15,
      opacity: 0.64,
      speed: 0.18,
      turbulence: 0.72,
      flowX: -0.025,
      flowY: 0.12,
      flowZ: 0.025,
      glow: false,
      wake: 0.84,
    }),
    signature: layer({
      name: "Fungal breathing spores",
      motion: "pulse",
      shape: "spore",
      color: 0x6fffd0,
      colorAlt: 0xc58ad9,
      minCount: 150,
      maxCount: 430,
      perFloor: 0.21,
      sizeMin: 0.065,
      sizeMax: 0.18,
      opacity: 0.66,
      speed: 0.22,
      turbulence: 0.8,
      flowX: 0.01,
      flowY: 0.08,
      flowZ: -0.015,
      glow: true,
      wake: 1.05,
    }),
    ceiling: ceiling({
      name: "Fungal slime drips",
      motion: "drip",
      shape: "drop",
      color: 0x5a8a62,
      colorAlt: 0x6a4a78,
      minCount: 55,
      maxCount: 170,
      perFloor: 0.09,
      sizeMin: 0.05,
      sizeMax: 0.15,
      opacity: 0.64,
      speed: 0.36,
      turbulence: 0.16,
      flowX: -0.02,
      flowY: -0.75,
      flowZ: 0.02,
      glow: true,
      wake: 0.25,
    }),
  },
  backrooms: {
    label: "stale dust, glitches, and yellow seepage",
    support: layer({
      name: "Backrooms stale dust",
      motion: "drift",
      shape: "mote",
      color: 0xb8ad72,
      colorAlt: 0x756f4d,
      minCount: 260,
      maxCount: 620,
      perFloor: 0.32,
      sizeMin: 0.05,
      sizeMax: 0.15,
      opacity: 0.48,
      speed: 0.1,
      turbulence: 0.18,
      flowX: 0.012,
      flowY: 0,
      flowZ: -0.01,
      glow: false,
      wake: 0.35,
    }),
    signature: layer({
      name: "Backrooms fluorescent glitches",
      motion: "flicker",
      shape: "block",
      color: 0xe5df91,
      colorAlt: 0xaab8a2,
      minCount: 80,
      maxCount: 220,
      perFloor: 0.1,
      sizeMin: 0.05,
      sizeMax: 0.12,
      opacity: 0.7,
      speed: 0.3,
      turbulence: 0.08,
      flowX: 0.03,
      flowY: 0,
      flowZ: 0,
      glow: true,
      wake: 0.3,
    }),
    ceiling: ceiling({
      name: "Backrooms yellow seepage",
      motion: "drip",
      shape: "drop",
      color: 0xc4b86a,
      colorAlt: 0x8a7e40,
      minCount: 45,
      maxCount: 140,
      perFloor: 0.07,
      sizeMin: 0.04,
      sizeMax: 0.12,
      opacity: 0.55,
      speed: 0.46,
      turbulence: 0.06,
      flowX: 0.01,
      flowY: -0.9,
      flowZ: 0,
    }),
  },
};

export const BIOME_PARTICLE_MOTION_ID: Record<BiomeParticleMotion, number> = {
  drift: 0,
  rise: 1,
  fall: 2,
  orbit: 3,
  flutter: 4,
  spark: 5,
  pulse: 6,
  flicker: 7,
  drip: 8,
};

export const BIOME_PARTICLE_SHAPE_ID: Record<BiomeParticleShape, number> = {
  mote: 0,
  streak: 1,
  flake: 2,
  ash: 3,
  wisp: 4,
  spore: 5,
  shard: 6,
  bubble: 7,
  block: 8,
  drop: 9,
  crumb: 10,
};

export function getBiomeParticleProfile(mood: DungeonMoodId): BiomeParticleProfile {
  return PROFILES[mood];
}

/** True when a layer is authored as ceiling precipitation (spawn bias + drip motion). */
export function isCeilingPrecipitationLayer(layer: BiomeParticleLayerProfile): boolean {
  return layer.motion === "drip";
}
