import type { DungeonMoodId } from "./DungeonMood";

export type BiomeParticleMotion =
  | "drift"
  | "rise"
  | "fall"
  | "orbit"
  | "flutter"
  | "spark"
  | "pulse"
  | "flicker";

export type BiomeParticleShape =
  | "mote"
  | "streak"
  | "flake"
  | "ash"
  | "wisp"
  | "spore"
  | "shard"
  | "bubble"
  | "block";

export interface BiomeParticleLayerProfile {
  name: string;
  motion: BiomeParticleMotion;
  shape: BiomeParticleShape;
  color: number;
  colorAlt: number;
  minCount: number;
  maxCount: number;
  perFloor: number;
  sizeMin: number;
  sizeMax: number;
  opacity: number;
  speed: number;
  turbulence: number;
  flowX: number;
  flowY: number;
  flowZ: number;
  glow: boolean;
  wake: number;
}

export interface BiomeParticleProfile {
  label: string;
  support: BiomeParticleLayerProfile;
  signature: BiomeParticleLayerProfile;
}

const layer = (
  config: Omit<BiomeParticleLayerProfile, "minCount" | "maxCount" | "perFloor"> &
    Partial<Pick<BiomeParticleLayerProfile, "minCount" | "maxCount" | "perFloor">>,
): BiomeParticleLayerProfile => ({
  minCount: 240,
  maxCount: 680,
  perFloor: 0.34,
  ...config,
});

const PROFILES: Record<DungeonMoodId, BiomeParticleProfile> = {
  ancient: {
    label: "dust and rune motes",
    support: layer({
      name: "Ancient limestone dust",
      motion: "drift",
      shape: "mote",
      color: 0xb9ad8f,
      colorAlt: 0x6f806f,
      sizeMin: 0.055,
      sizeMax: 0.17,
      opacity: 0.5,
      speed: 0.18,
      turbulence: 0.24,
      flowX: 0.025,
      flowY: 0.01,
      flowZ: -0.015,
      glow: false,
      wake: 0.42,
    }),
    signature: layer({
      name: "Ancient orbiting rune motes",
      motion: "orbit",
      shape: "block",
      color: 0xd6b66d,
      colorAlt: 0x74b6a1,
      minCount: 110,
      maxCount: 320,
      perFloor: 0.16,
      sizeMin: 0.05,
      sizeMax: 0.11,
      opacity: 0.62,
      speed: 0.22,
      turbulence: 0.34,
      flowX: 0,
      flowY: 0.015,
      flowZ: 0,
      glow: true,
      wake: 0.82,
    }),
  },
  molten: {
    label: "embers and hot cinders",
    support: layer({
      name: "Molten falling cinders",
      motion: "fall",
      shape: "ash",
      color: 0x6f4430,
      colorAlt: 0xb75b32,
      sizeMin: 0.045,
      sizeMax: 0.14,
      opacity: 0.48,
      speed: 0.25,
      turbulence: 0.32,
      flowX: 0.03,
      flowY: -0.12,
      flowZ: 0.01,
      glow: false,
      wake: 0.5,
    }),
    signature: layer({
      name: "Molten rising embers",
      motion: "rise",
      shape: "streak",
      color: 0xff7a28,
      colorAlt: 0xffd27a,
      minCount: 220,
      maxCount: 620,
      perFloor: 0.3,
      sizeMin: 0.06,
      sizeMax: 0.2,
      opacity: 0.78,
      speed: 0.48,
      turbulence: 0.48,
      flowX: 0.05,
      flowY: 0.62,
      flowZ: -0.02,
      glow: true,
      wake: 0.9,
    }),
  },
  frost: {
    label: "snow and ice crystals",
    support: layer({
      name: "Frost powder snow",
      motion: "fall",
      shape: "flake",
      color: 0xc4ddea,
      colorAlt: 0x7899b4,
      minCount: 320,
      maxCount: 760,
      perFloor: 0.42,
      sizeMin: 0.045,
      sizeMax: 0.14,
      opacity: 0.62,
      speed: 0.2,
      turbulence: 0.52,
      flowX: 0.08,
      flowY: -0.34,
      flowZ: 0.02,
      glow: false,
      wake: 0.62,
    }),
    signature: layer({
      name: "Frost suspended ice crystals",
      motion: "flutter",
      shape: "shard",
      color: 0xeaf8ff,
      colorAlt: 0x72d4ff,
      minCount: 130,
      maxCount: 360,
      perFloor: 0.18,
      sizeMin: 0.05,
      sizeMax: 0.13,
      opacity: 0.58,
      speed: 0.16,
      turbulence: 0.42,
      flowX: -0.02,
      flowY: -0.05,
      flowZ: 0.035,
      glow: true,
      wake: 0.72,
    }),
  },
  grim: {
    label: "soot and pale wisps",
    support: layer({
      name: "Grim descending soot",
      motion: "fall",
      shape: "ash",
      color: 0x817d70,
      colorAlt: 0x3c463c,
      sizeMin: 0.06,
      sizeMax: 0.18,
      opacity: 0.5,
      speed: 0.15,
      turbulence: 0.38,
      flowX: -0.025,
      flowY: -0.16,
      flowZ: 0.018,
      glow: false,
      wake: 0.56,
    }),
    signature: layer({
      name: "Grim grave wisps",
      motion: "pulse",
      shape: "wisp",
      color: 0x8ebd8b,
      colorAlt: 0xc6d0aa,
      minCount: 90,
      maxCount: 260,
      perFloor: 0.13,
      sizeMin: 0.085,
      sizeMax: 0.22,
      opacity: 0.42,
      speed: 0.13,
      turbulence: 0.45,
      flowX: 0.01,
      flowY: 0.08,
      flowZ: -0.015,
      glow: true,
      wake: 0.94,
    }),
  },
  verdant: {
    label: "pollen and fireflies",
    support: layer({
      name: "Verdant drifting pollen",
      motion: "drift",
      shape: "spore",
      color: 0xa8c77c,
      colorAlt: 0x6e8b58,
      minCount: 300,
      maxCount: 720,
      perFloor: 0.38,
      sizeMin: 0.06,
      sizeMax: 0.18,
      opacity: 0.58,
      speed: 0.2,
      turbulence: 0.56,
      flowX: 0.035,
      flowY: 0.025,
      flowZ: -0.02,
      glow: false,
      wake: 0.7,
    }),
    signature: layer({
      name: "Verdant fireflies",
      motion: "orbit",
      shape: "mote",
      color: 0xbaff78,
      colorAlt: 0x61e0ad,
      minCount: 110,
      maxCount: 300,
      perFloor: 0.14,
      sizeMin: 0.075,
      sizeMax: 0.17,
      opacity: 0.75,
      speed: 0.25,
      turbulence: 0.78,
      flowX: 0,
      flowY: 0.04,
      flowZ: 0,
      glow: true,
      wake: 1,
    }),
  },
  ash: {
    label: "ashfall and warm embers",
    support: layer({
      name: "Ash biome ashfall",
      motion: "fall",
      shape: "ash",
      color: 0x9b8c82,
      colorAlt: 0x544f50,
      minCount: 380,
      maxCount: 820,
      perFloor: 0.46,
      sizeMin: 0.065,
      sizeMax: 0.23,
      opacity: 0.62,
      speed: 0.24,
      turbulence: 0.64,
      flowX: 0.11,
      flowY: -0.3,
      flowZ: -0.035,
      glow: false,
      wake: 0.75,
    }),
    signature: layer({
      name: "Ash biome buried embers",
      motion: "rise",
      shape: "mote",
      color: 0xe79054,
      colorAlt: 0xf3c889,
      minCount: 80,
      maxCount: 230,
      perFloor: 0.11,
      sizeMin: 0.055,
      sizeMax: 0.14,
      opacity: 0.58,
      speed: 0.2,
      turbulence: 0.38,
      flowX: -0.02,
      flowY: 0.18,
      flowZ: 0.02,
      glow: true,
      wake: 0.76,
    }),
  },
  iron: {
    label: "metal dust and magnetic sparks",
    support: layer({
      name: "Iron filings",
      motion: "fall",
      shape: "shard",
      color: 0x87919a,
      colorAlt: 0x4c5b62,
      sizeMin: 0.04,
      sizeMax: 0.13,
      opacity: 0.48,
      speed: 0.18,
      turbulence: 0.3,
      flowX: 0,
      flowY: -0.12,
      flowZ: 0.01,
      glow: false,
      wake: 0.5,
    }),
    signature: layer({
      name: "Iron magnetic sparks",
      motion: "spark",
      shape: "streak",
      color: 0x78c6e4,
      colorAlt: 0xffb45e,
      minCount: 130,
      maxCount: 380,
      perFloor: 0.18,
      sizeMin: 0.055,
      sizeMax: 0.16,
      opacity: 0.76,
      speed: 0.5,
      turbulence: 0.28,
      flowX: 0.18,
      flowY: 0.06,
      flowZ: -0.04,
      glow: true,
      wake: 1.12,
    }),
  },
  obsidian: {
    label: "glass splinters and void motes",
    support: layer({
      name: "Obsidian glass dust",
      motion: "drift",
      shape: "shard",
      color: 0x6e4a73,
      colorAlt: 0x352a46,
      sizeMin: 0.055,
      sizeMax: 0.17,
      opacity: 0.5,
      speed: 0.14,
      turbulence: 0.25,
      flowX: -0.02,
      flowY: 0.02,
      flowZ: 0.02,
      glow: false,
      wake: 0.48,
    }),
    signature: layer({
      name: "Obsidian anti-gravity splinters",
      motion: "rise",
      shape: "shard",
      color: 0xbe65d1,
      colorAlt: 0xe08a89,
      minCount: 150,
      maxCount: 420,
      perFloor: 0.2,
      sizeMin: 0.06,
      sizeMax: 0.16,
      opacity: 0.68,
      speed: 0.22,
      turbulence: 0.34,
      flowX: 0.025,
      flowY: 0.28,
      flowZ: -0.02,
      glow: true,
      wake: 1.05,
    }),
  },
  sunken: {
    label: "drizzle and rising bubbles",
    support: layer({
      name: "Sunken suspended droplets",
      motion: "fall",
      shape: "streak",
      color: 0x6c9996,
      colorAlt: 0x355f60,
      minCount: 300,
      maxCount: 720,
      perFloor: 0.4,
      sizeMin: 0.045,
      sizeMax: 0.15,
      opacity: 0.48,
      speed: 0.3,
      turbulence: 0.25,
      flowX: 0.015,
      flowY: -0.42,
      flowZ: 0.02,
      glow: false,
      wake: 0.58,
    }),
    signature: layer({
      name: "Sunken rising bubbles",
      motion: "rise",
      shape: "bubble",
      color: 0xa2e2d7,
      colorAlt: 0x59aeb1,
      minCount: 130,
      maxCount: 350,
      perFloor: 0.17,
      sizeMin: 0.07,
      sizeMax: 0.18,
      opacity: 0.55,
      speed: 0.28,
      turbulence: 0.5,
      flowX: 0.02,
      flowY: 0.36,
      flowZ: -0.01,
      glow: true,
      wake: 0.9,
    }),
  },
  fungal: {
    label: "spore bloom and mycelial pulses",
    support: layer({
      name: "Fungal spore cloud",
      motion: "rise",
      shape: "spore",
      color: 0x8ec6a7,
      colorAlt: 0x8b6996,
      minCount: 360,
      maxCount: 820,
      perFloor: 0.45,
      sizeMin: 0.05,
      sizeMax: 0.15,
      opacity: 0.64,
      speed: 0.18,
      turbulence: 0.72,
      flowX: -0.025,
      flowY: 0.12,
      flowZ: 0.025,
      glow: false,
      wake: 0.84,
    }),
    signature: layer({
      name: "Fungal breathing spores",
      motion: "pulse",
      shape: "spore",
      color: 0x6fffd0,
      colorAlt: 0xc58ad9,
      minCount: 150,
      maxCount: 430,
      perFloor: 0.21,
      sizeMin: 0.065,
      sizeMax: 0.18,
      opacity: 0.66,
      speed: 0.22,
      turbulence: 0.8,
      flowX: 0.01,
      flowY: 0.08,
      flowZ: -0.015,
      glow: true,
      wake: 1.05,
    }),
  },
  backrooms: {
    label: "stale dust and fluorescent glitches",
    support: layer({
      name: "Backrooms stale dust",
      motion: "drift",
      shape: "mote",
      color: 0xb8ad72,
      colorAlt: 0x756f4d,
      minCount: 260,
      maxCount: 620,
      perFloor: 0.32,
      sizeMin: 0.05,
      sizeMax: 0.15,
      opacity: 0.48,
      speed: 0.1,
      turbulence: 0.18,
      flowX: 0.012,
      flowY: 0,
      flowZ: -0.01,
      glow: false,
      wake: 0.35,
    }),
    signature: layer({
      name: "Backrooms fluorescent glitches",
      motion: "flicker",
      shape: "block",
      color: 0xe5df91,
      colorAlt: 0xaab8a2,
      minCount: 80,
      maxCount: 220,
      perFloor: 0.1,
      sizeMin: 0.05,
      sizeMax: 0.12,
      opacity: 0.7,
      speed: 0.3,
      turbulence: 0.08,
      flowX: 0.03,
      flowY: 0,
      flowZ: 0,
      glow: true,
      wake: 0.3,
    }),
  },
};

export const BIOME_PARTICLE_MOTION_ID: Record<BiomeParticleMotion, number> = {
  drift: 0,
  rise: 1,
  fall: 2,
  orbit: 3,
  flutter: 4,
  spark: 5,
  pulse: 6,
  flicker: 7,
};

export const BIOME_PARTICLE_SHAPE_ID: Record<BiomeParticleShape, number> = {
  mote: 0,
  streak: 1,
  flake: 2,
  ash: 3,
  wisp: 4,
  spore: 5,
  shard: 6,
  bubble: 7,
  block: 8,
};

export function getBiomeParticleProfile(mood: DungeonMoodId): BiomeParticleProfile {
  return PROFILES[mood];
}
